### ISSUE TITLE
THIS ISNT AN ISSUE:

### ISSUE THREAD

**Issue by ashercn97** [jettblu/nanograd#1]
Omg sorry to make an issue but this is so cool!! Im gonna use this rn!

**Comment by jettblu** [comment]
Awesome! Keep in mind the value-based autograd system is functional, but the tensor library is still under construction. 

You can also try the [neural network playground](https://www.nanograd.xyz/), which uses wasm web bindings, to let you run nanograd in your browser.

**Comment by ashercn97** [comment]
@jettblu  Oooh ty for letting me know!!

**Comment by ashercn97** [comment]
@jettblu  trying out the website rn and omg its so cool!!

**Comment by ashercn97** [comment]
Also, do you know if there are things like google colab but for rust?
